version: "3.8"
services:
  web:
    build: .
    command: ["python", "run.py"]
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SYMS=btcusdt,ethusdt
    volumes:
      - ./:/app
